version: "3"
services:
  web:
    image: account-front
    container_name: account-front
    hostname: account-front
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "4000:80"

  deploy:
    image: laxeder/account
    volumes: 
      - ./app:/usr/share/nginx/html
    ports:
      - 8080:80
