name: Workflow - Push em Dockerhub

on:
  push:
    branches:
      - "dev"
env:
  IMAGE_NAME: envirioment-node

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: build do Angular
        uses: actions/checkout@v2
        run: |
          sudo apt install nodejs
          sudo apt install npm
          sudo npm install --global yarn
          sudo yarn
          sudo npm run build
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{secrets.DOCKERHUB_USERNAME}}/account:latest
