name: Workflow - Push em Dockerhub

on:
  push:
    branches:
      - stagging

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"
          
      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: Build and push 
        uses: docker/build-push-action@v2  
        with: 
          context: ./ 
          file: ./Dockerfile 
          push: true 
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/account:latest

      # - name: Build and push
      #   uses: docker/build-push-action@v3
      #   with:
      #     push: true
      #     tags: ${{secrets.DOCKERHUB_USERNAME}}/account:latest 

          